// spellchecker_test.ts
// Auto-generated: 500 literal lines for spellchecker test

export const testLines: string[] = [
  "Thiss line has a speling error.",
  "The quick brown fox jumps over the lazy dog.",
  "I liek to write cod everyday.",
  "Spellchecker should detect mispelled wrds.",
  "This sentence is perfectly fine.",
  "Teh rain in spain falls mainly on the plain.",
  "Correct spelling is important in proffesional writing.",
  "The computar is running very smoothly.",
  "Some words arre repeated repeated incorrectly.",
  "English has many weird spellings.",
  "Datta integrity is crucial in databases.",
  "Som people forget double letters like accomodate.",
  "Beutiful day outside with sunshine.",
  "The sun set slowly behind the mountan.",
  "This is a CORRECTLY capitalized sentence.",
  "Check for RANDOM capitalization Errors here.",
  "Typing fast can cause speeling mistakes.",
  "I have recieve the package today.",
  "Simple sentnce with missng vowels.",
  "12345 testnumbers insideaword987.",
  "Punctuation,test,case,without,spaces.",
  "Omg!!!! Too many exclamationsssss.",
  "Thisss worrrd shouldd be flaged.",
  "CamelCaseWordShouldBeTested.",
  "testCASEwithMixedUPletters.",
  "LOWERCASE all correct words here.",
  "UPPERCASE ALLCORRECTWORDS TOO.",
  "MixEd CaSe WIT out Sense.",
  "Numberslike2fastshouldbeseparated.",
  "The differnce between there and their.",
  "Weather or wether the words matter.",
  "Thay went to the store yesterday.",
  "She doesnt know how to spel \"necessary\".",
  "Some ppl use txt spk 4 chatting.",
  "CreativeInventedWoordForTesting.",
  "An extraaa a at the endd.",
  "Wordswith—unusual—dashes—inside.",
  "Odd’s use of apostrophe’s wrongly.",
  "End with a question markk??",
  "Colons: are: used: incorrectlyy:",
  "Quote without ending mark “Example.",
  "Sentence has no ending period",
  "Random gibber: asdlfkj qweorui mnzx.",
  "Coffeee tastes bettr in the morning.",
  "Definately is a common misspelling.",
  "She beleives in her abilitiess.",
  "Occured twice in thiss doccumnt.",
  "Freindship is spelt incorectly.",
  "Finally, the lasst line is done.",
  "Thiss line has a speling error.",
  "The quick brown fox jumps over the lazy dog.",
  "I liek to write cod everyday.",
  "Spellchecker should detect mispelled wrds.",
  "This sentence is perfectly fine.",
  "Teh rain in spain falls mainly on the plain.",
  "Correct spelling is important in proffesional writing.",
  "The computar is running very smoothly.",
  "Some words arre repeated repeated incorrectly.",
  "English has many weird spellings.",
  "Datta integrity is crucial in databases.",
  "Som people forget double letters like accomodate.",
  "Beutiful day outside with sunshine.",
  "The sun set slowly behind the mountan.",
  "This is a CORRECTLY capitalized sentence.",
  "Check for RANDOM capitalization Errors here.",
  "Typing fast can cause speeling mistakes.",
  "I have recieve the package today.",
  "Simple sentnce with missng vowels.",
  "12345 testnumbers insideaword987.",
  "Punctuation,test,case,without,spaces.",
  "Omg!!!! Too many exclamationsssss.",
  "Thisss worrrd shouldd be flaged.",
  "CamelCaseWordShouldBeTested.",
  "testCASEwithMixedUPletters.",
  "LOWERCASE all correct words here.",
  "UPPERCASE ALLCORRECTWORDS TOO.",
  "MixEd CaSe WIT out Sense.",
  "Numberslike2fastshouldbeseparated.",
  "The differnce between there and their.",
  "Weather or wether the words matter.",
  "Thay went to the store yesterday.",
  "She doesnt know how to spel \"necessary\".",
  "Some ppl use txt spk 4 chatting.",
  "CreativeInventedWoordForTesting.",
  "An extraaa a at the endd.",
  "Wordswith—unusual—dashes—inside.",
  "Odd’s use of apostrophe’s wrongly.",
  "End with a question markk??",
  "Colons: are: used: incorrectlyy:",
  "Quote without ending mark “Example.",
  "Sentence has no ending period",
  "Random gibber: asdlfkj qweorui mnzx.",
  "Coffeee tastes bettr in the morning.",
  "Definately is a common misspelling.",
  "She beleives in her abilitiess.",
  "Occured twice in thiss doccumnt.",
  "Freindship is spelt incorectly.",
  "Finally, the lasst line is done.",
  "THISS LINE HAS A SPELING ERROR.",
  "THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG.",
  "I LIEK TO WRITE COD EVERYDAY.",
  "SPELLCHECKER SHOULD DETECT MISPELLED WRDS.",
  "THIS SENTENCE IS PERFECTLY FINE.",
  "TEH RAIN IN SPAIN FALLS MAINLY ON THE PLAIN.",
  "CORRECT SPELLING IS IMPORTANT IN PROFFESIONAL WRITING.",
  "THE COMPUTAR IS RUNNING VERY SMOOTHLY.",
  "SOME WORDS ARRE REPEATED REPEATED INCORRECTLY.",
  "ENGLISH HAS MANY WEIRD SPELLINGS.",
  "DATTA INTEGRITY IS CRUCIAL IN DATABASES.",
  "SOM PEOPLE FORGET DOUBLE LETTERS LIKE ACCOMODATE.",
  "BEUTIFUL DAY OUTSIDE WITH SUNSHINE.",
  "THE SUN SET SLOWLY BEHIND THE MOUNTAN.",
  "THIS IS A CORRECTLY CAPITALIZED SENTENCE.",
  "CHECK FOR RANDOM CAPITALIZATION ERRORS HERE.",
  "TYPING FAST CAN CAUSE SPEELING MISTAKES.",
  "I HAVE RECIEVE THE PACKAGE TODAY.",
  "SIMPLE SENTNCE WITH MISSNG VOWELS.",
  "12345 TESTNUMBERS INSIDEAWORD987.",
  "PUNCTUATION,TEST,CASE,WITHOUT,SPACES.",
  "OMG!!!! TOO MANY EXCLAMATIONSSSSS.",
  "THISSS WORRRD SHOULDD BE FLAGED.",
  "CAMELCASEWORDSHOULDBETESTED.",
  "TESTCASEWITHMIXEDUPLETTERS.",
  "LOWERCASE ALL CORRECT WORDS HERE.",
  "UPPERCASE ALLCORRECTWORDS TOO.",
  "MIXED CASE WIT OUT SENSE.",
  "NUMBERSLIKE2FASTSHOULDBESEPARATED.",
  "THE DIFFERNCE BETWEEN THERE AND THEIR.",
  "WEATHER OR WETHER THE WORDS MATTER.",
  "THAY WENT TO THE STORE YESTERDAY.",
  "SHE DOESNT KNOW HOW TO SPEL \"NECESSARY\".",
  "SOME PPL USE TXT SPK 4 CHATTING.",
  "CREATIVEINVENTEDWOORDFORTESTING.",
  "AN EXTRAAA A AT THE ENDD.",
  "WORDSWITH—UNUSUAL—DASHES—INSIDE.",
  "ODD’S USE OF APOSTROPHE’S WRONGLY.",
  "END WITH A QUESTION MARKK??",
  "COLONS: ARE: USED: INCORRECTLYY:",
  "QUOTE WITHOUT ENDING MARK “EXAMPLE.",
  "SENTENCE HAS NO ENDING PERIOD",
  "RANDOM GIBBER: ASDLFKJ QWEORUI MNZX.",
  "COFFEEE TASTES BETTR IN THE MORNING.",
  "DEFINATELY IS A COMMON MISSPELLING.",
  "SHE BELEIVES IN HER ABILITIESS.",
  "OCCURED TWICE IN THISS DOCCUMNT.",
  "FREINDSHIP IS SPELT INCORECTLY.",
  "FINALLY, THE LASST LINE IS DONE.",
  "Thiss line has a speling error. ###",
  "The quick brown fox jumps over the lazy dog. ###",
  "I liek to write cod everyday. ###",
  "Spellchecker should detect mispelled wrds. ###",
  "This sentence is perfectly fine. ###",
  "Teh rain in spain falls mainly on the plain. ###",
  "Correct spelling is important in proffesional writing. ###",
  "The computar is running very smoothly. ###",
  "Some words arre repeated repeated incorrectly. ###",
  "English has many weird spellings. ###",
  "Datta integrity is crucial in databases. ###",
  "Som people forget double letters like accomodate. ###",
  "Beutiful day outside with sunshine. ###",
  "The sun set slowly behind the mountan. ###",
  "This is a CORRECTLY capitalized sentence. ###",
  "Check for RANDOM capitalization Errors here. ###",
  "Typing fast can cause speeling mistakes. ###",
  "I have recieve the package today. ###",
  "Simple sentnce with missng vowels. ###",
  "12345 testnumbers insideaword987. ###",
  "Punctuation,test,case,without,spaces. ###",
  "Omg!!!! Too many exclamationsssss. ###",
  "Thisss worrrd shouldd be flaged. ###",
  "CamelCaseWordShouldBeTested. ###",
  "testCASEwithMixedUPletters. ###",
  "LOWERCASE all correct words here. ###",
  "UPPERCASE ALLCORRECTWORDS TOO. ###",
  "MixEd CaSe WIT out Sense. ###",
  "Numberslike2fastshouldbeseparated. ###",
  "The differnce between there and their. ###",
  "Weather or wether the words matter. ###",
  "Thay went to the store yesterday. ###",
  "She doesnt know how to spel \"necessary\". ###",
  "Some ppl use txt spk 4 chatting. ###",
  "CreativeInventedWoordForTesting. ###",
  "An extraaa a at the endd. ###",
  "Wordswith—unusual—dashes—inside. ###",
  "Odd’s use of apostrophe’s wrongly. ###",
  "End with a question markk?? ###",
  "Colons: are: used: incorrectlyy: ###",
  "Quote without ending mark “Example. ###",
  "Sentence has no ending period ###",
  "Random gibber: asdlfkj qweorui mnzx. ###",
  "Coffeee tastes bettr in the morning. ###",
  "Definately is a common misspelling. ###",
  "She beleives in her abilitiess. ###",
  "Occured twice in thiss doccumnt. ###",
  "Freindship is spelt incorectly. ###",
  "Finally, the lasst line is done. ###",
  "THISS LINE HAS A SPELING ERROR.",
  "THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG.",
  "I LIEK TO WRITE COD EVERYDAY.",
  "SPELLCHECKER SHOULD DETECT MISPELLED WRDS.",
  "THIS SENTENCE IS PERFECTLY FINE.",
  "TEH RAIN IN SPAIN FALLS MAINLY ON THE PLAIN.",
  "CORRECT SPELLING IS IMPORTANT IN PROFFESIONAL WRITING.",
  "THE COMPUTAR IS RUNNING VERY SMOOTHLY.",
  "SOME WORDS ARRE REPEATED REPEATED INCORRECTLY.",
  "ENGLISH HAS MANY WEIRD SPELLINGS.",
  "DATTA INTEGRITY IS CRUCIAL IN DATABASES.",
  "SOM PEOPLE FORGET DOUBLE LETTERS LIKE ACCOMODATE.",
  "BEUTIFUL DAY OUTSIDE WITH SUNSHINE.",
  "THE SUN SET SLOWLY BEHIND THE MOUNTAN.",
  "THIS IS A CORRECTLY CAPITALIZED SENTENCE.",
  "CHECK FOR RANDOM CAPITALIZATION ERRORS HERE.",
  "TYPING FAST CAN CAUSE SPEELING MISTAKES.",
  "I HAVE RECIEVE THE PACKAGE TODAY.",
  "SIMPLE SENTNCE WITH MISSNG VOWELS.",
  "12345 TESTNUMBERS INSIDEAWORD987.",
  "PUNCTUATION,TEST,CASE,WITHOUT,SPACES.",
  "OMG!!!! TOO MANY EXCLAMATIONSSSSS.",
  "THISSS WORRRD SHOULDD BE FLAGED.",
  "CAMELCASEWORDSHOULDBETESTED.",
  "TESTCASEWITHMIXEDUPLETTERS.",
  "LOWERCASE ALL CORRECT WORDS HERE.",
  "UPPERCASE ALLCORRECTWORDS TOO.",
  "MIXED CASE WIT OUT SENSE.",
  "NUMBERSLIKE2FASTSHOULDBESEPARATED.",
  "THE DIFFERNCE BETWEEN THERE AND THEIR.",
  "WEATHER OR WETHER THE WORDS MATTER.",
  "THAY WENT TO THE STORE YESTERDAY.",
  "SHE DOESNT KNOW HOW TO SPEL \"NECESSARY\".",
  "SOME PPL USE TXT SPK 4 CHATTING.",
  "CREATIVEINVENTEDWOORDFORTESTING.",
  "AN EXTRAAA A AT THE ENDD.",
  "WORDSWITH—UNUSUAL—DASHES—INSIDE.",
  "ODD’S USE OF APOSTROPHE’S WRONGLY.",
  "END WITH A QUESTION MARKK??",
  "COLONS: ARE: USED: INCORRECTLYY:",
  "QUOTE WITHOUT ENDING MARK “EXAMPLE.",
  "SENTENCE HAS NO ENDING PERIOD",
  "RANDOM GIBBER: ASDLFKJ QWEORUI MNZX.",
  "COFFEEE TASTES BETTR IN THE MORNING.",
  "DEFINATELY IS A COMMON MISSPELLING.",
  "SHE BELEIVES IN HER ABILITIESS.",
  "OCCURED TWICE IN THISS DOCCUMNT.",
  "FREINDSHIP IS SPELT INCORECTLY.",
  "FINALLY, THE LASST LINE IS DONE.",
  "Thiss line has a speling error.",
  "The quick brown fox jumps over the lazy dog.",
  "I liek to write cod everyday.",
  "Spellchecker should detect mispelled wrds.",
  "This sentence is perfectly fine.",
  "Teh rain in spain falls mainly on the plain.",
  "Correct spelling is important in proffesional writing.",
  "The computar is running very smoothly.",
  "Some words arre repeated repeated incorrectly.",
  "English has many weird spellings.",
  "Datta integrity is crucial in databases.",
  "Som people forget double letters like accomodate.",
  "Beutiful day outside with sunshine.",
  "The sun set slowly behind the mountan.",
  "This is a CORRECTLY capitalized sentence.",
  "Check for RANDOM capitalization Errors here.",
  "Typing fast can cause speeling mistakes.",
  "I have recieve the package today.",
  "Simple sentnce with missng vowels.",
  "12345 testnumbers insideaword987.",
  "Punctuation,test,case,without,spaces.",
  "Omg!!!! Too many exclamationsssss.",
  "Thisss worrrd shouldd be flaged.",
  "CamelCaseWordShouldBeTested.",
  "testCASEwithMixedUPletters.",
  "LOWERCASE all correct words here.",
  "UPPERCASE ALLCORRECTWORDS TOO.",
  "MixEd CaSe WIT out Sense.",
  "Numberslike2fastshouldbeseparated.",
  "The differnce between there and their.",
  "Weather or wether the words matter.",
  "Thay went to the store yesterday.",
  "She doesnt know how to spel \"necessary\".",
  "Some ppl use txt spk 4 chatting.",
  "CreativeInventedWoordForTesting.",
  "An extraaa a at the endd.",
  "Wordswith—unusual—dashes—inside.",
  "Odd’s use of apostrophe’s wrongly.",
  "End with a question markk??",
  "Colons: are: used: incorrectlyy:",
  "Quote without ending mark “Example.",
  "Sentence has no ending period",
  "Random gibber: asdlfkj qweorui mnzx.",
  "Coffeee tastes bettr in the morning.",
  "Definately is a common misspelling.",
  "She beleives in her abilitiess.",
  "Occured twice in thiss doccumnt.",
  "Freindship is spelt incorectly.",
  "Finally, the lasst line is done.",
  "THISS LINE HAS A SPELING ERROR. ###",
  "THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG. ###",
  "I LIEK TO WRITE COD EVERYDAY. ###",
  "SPELLCHECKER SHOULD DETECT MISPELLED WRDS. ###",
  "THIS SENTENCE IS PERFECTLY FINE. ###",
  "TEH RAIN IN SPAIN FALLS MAINLY ON THE PLAIN. ###",
  "CORRECT SPELLING IS IMPORTANT IN PROFFESIONAL WRITING. ###",
  "THE COMPUTAR IS RUNNING VERY SMOOTHLY. ###",
  "SOME WORDS ARRE REPEATED REPEATED INCORRECTLY. ###",
  "ENGLISH HAS MANY WEIRD SPELLINGS. ###",
  "DATTA INTEGRITY IS CRUCIAL IN DATABASES. ###",
  "SOM PEOPLE FORGET DOUBLE LETTERS LIKE ACCOMODATE. ###",
  "BEUTIFUL DAY OUTSIDE WITH SUNSHINE. ###",
  "THE SUN SET SLOWLY BEHIND THE MOUNTAN. ###",
  "THIS IS A CORRECTLY CAPITALIZED SENTENCE. ###",
  "CHECK FOR RANDOM CAPITALIZATION ERRORS HERE. ###",
  "TYPING FAST CAN CAUSE SPEELING MISTAKES. ###",
  "I HAVE RECIEVE THE PACKAGE TODAY. ###",
  "SIMPLE SENTNCE WITH MISSNG VOWELS. ###",
  "12345 TESTNUMBERS INSIDEAWORD987. ###",
  "PUNCTUATION,TEST,CASE,WITHOUT,SPACES. ###",
  "OMG!!!! TOO MANY EXCLAMATIONSSSSS. ###",
  "THISSS WORRRD SHOULDD BE FLAGED. ###",
  "CAMELCASEWORDSHOULDBETESTED. ###",
  "TESTCASEWITHMIXEDUPLETTERS. ###",
  "LOWERCASE ALL CORRECT WORDS HERE. ###",
  "UPPERCASE ALLCORRECTWORDS TOO. ###",
  "MIXED CASE WIT OUT SENSE. ###",
  "NUMBERSLIKE2FASTSHOULDBESEPARATED. ###",
  "THE DIFFERNCE BETWEEN THERE AND THEIR. ###",
  "WEATHER OR WETHER THE WORDS MATTER. ###",
  "THAY WENT TO THE STORE YESTERDAY. ###",
  "SHE DOESNT KNOW HOW TO SPEL \"NECESSARY\". ###",
  "SOME PPL USE TXT SPK 4 CHATTING. ###",
  "CREATIVEINVENTEDWOORDFORTESTING. ###",
  "AN EXTRAAA A AT THE ENDD. ###",
  "WORDSWITH—UNUSUAL—DASHES—INSIDE. ###",
  "ODD’S USE OF APOSTROPHE’S WRONGLY. ###",
  "END WITH A QUESTION MARKK?? ###",
  "COLONS: ARE: USED: INCORRECTLYY: ###",
  "QUOTE WITHOUT ENDING MARK “EXAMPLE. ###",
  "SENTENCE HAS NO ENDING PERIOD ###",
  "RANDOM GIBBER: ASDLFKJ QWEORUI MNZX. ###",
  "COFFEEE TASTES BETTR IN THE MORNING. ###",
  "DEFINATELY IS A COMMON MISSPELLING. ###",
  "SHE BELEIVES IN HER ABILITIESS. ###",
  "OCCURED TWICE IN THISS DOCCUMNT. ###",
  "FREINDSHIP IS SPELT INCORECTLY. ###",
  "FINALLY, THE LASST LINE IS DONE. ###",
  "Thiss line has a speling error.",
  "The quick brown fox jumps over the lazy dog.",
  "I liek to write cod everyday.",
  "Spellchecker should detect mispelled wrds.",
  "This sentence is perfectly fine.",
  "Teh rain in spain falls mainly on the plain.",
  "Correct spelling is important in proffesional writing.",
  "The computar is running very smoothly.",
  "Some words arre repeated repeated incorrectly.",
  "English has many weird spellings.",
  "Datta integrity is crucial in databases.",
  "Som people forget double letters like accomodate.",
  "Beutiful day outside with sunshine.",
  "The sun set slowly behind the mountan.",
  "This is a CORRECTLY capitalized sentence.",
  "Check for RANDOM capitalization Errors here.",
  "Typing fast can cause speeling mistakes.",
  "I have recieve the package today.",
  "Simple sentnce with missng vowels.",
  "12345 testnumbers insideaword987.",
  "Punctuation,test,case,without,spaces.",
  "Omg!!!! Too many exclamationsssss.",
  "Thisss worrrd shouldd be flaged.",
  "CamelCaseWordShouldBeTested.",
  "testCASEwithMixedUPletters.",
  "LOWERCASE all correct words here.",
  "UPPERCASE ALLCORRECTWORDS TOO.",
  "MixEd CaSe WIT out Sense.",
  "Numberslike2fastshouldbeseparated.",
  "The differnce between there and their.",
  "Weather or wether the words matter.",
  "Thay went to the store yesterday.",
  "She doesnt know how to spel \"necessary\".",
  "Some ppl use txt spk 4 chatting.",
  "CreativeInventedWoordForTesting.",
  "An extraaa a at the endd.",
  "Wordswith—unusual—dashes—inside.",
  "Odd’s use of apostrophe’s wrongly.",
  "End with a question markk??",
  "Colons: are: used: incorrectlyy:",
  "Quote without ending mark “Example.",
  "Sentence has no ending period",
  "Random gibber: asdlfkj qweorui mnzx.",
  "Coffeee tastes bettr in the morning.",
  "Definately is a common misspelling.",
  "She beleives in her abilitiess.",
  "Occured twice in thiss doccumnt.",
  "Freindship is spelt incorectly.",
  "Finally, the lasst line is done.",
  "THISS LINE HAS A SPELING ERROR.",
  "THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG.",
  "I LIEK TO WRITE COD EVERYDAY.",
  "SPELLCHECKER SHOULD DETECT MISPELLED WRDS.",
  "THIS SENTENCE IS PERFECTLY FINE.",
  "TEH RAIN IN SPAIN FALLS MAINLY ON THE PLAIN.",
  "CORRECT SPELLING IS IMPORTANT IN PROFFESIONAL WRITING.",
  "THE COMPUTAR IS RUNNING VERY SMOOTHLY.",
  "SOME WORDS ARRE REPEATED REPEATED INCORRECTLY.",
  "ENGLISH HAS MANY WEIRD SPELLINGS.",
  "DATTA INTEGRITY IS CRUCIAL IN DATABASES.",
  "SOM PEOPLE FORGET DOUBLE LETTERS LIKE ACCOMODATE.",
  "BEUTIFUL DAY OUTSIDE WITH SUNSHINE.",
  "THE SUN SET SLOWLY BEHIND THE MOUNTAN.",
  "THIS IS A CORRECTLY CAPITALIZED SENTENCE.",
  "CHECK FOR RANDOM CAPITALIZATION ERRORS HERE.",
  "TYPING FAST CAN CAUSE SPEELING MISTAKES.",
  "I HAVE RECIEVE THE PACKAGE TODAY.",
  "SIMPLE SENTNCE WITH MISSNG VOWELS.",
  "12345 TESTNUMBERS INSIDEAWORD987.",
  "PUNCTUATION,TEST,CASE,WITHOUT,SPACES.",
  "OMG!!!! TOO MANY EXCLAMATIONSSSSS.",
  "THISSS WORRRD SHOULDD BE FLAGED.",
  "CAMELCASEWORDSHOULDBETESTED.",
  "TESTCASEWITHMIXEDUPLETTERS.",
  "LOWERCASE ALL CORRECT WORDS HERE.",
  "UPPERCASE ALLCORRECTWORDS TOO.",
  "MIXED CASE WIT OUT SENSE.",
  "NUMBERSLIKE2FASTSHOULDBESEPARATED.",
  "THE DIFFERNCE BETWEEN THERE AND THEIR.",
  "WEATHER OR WETHER THE WORDS MATTER.",
  "THAY WENT TO THE STORE YESTERDAY.",
  "SHE DOESNT KNOW HOW TO SPEL \"NECESSARY\".",
  "SOME PPL USE TXT SPK 4 CHATTING.",
  "CREATIVEINVENTEDWOORDFORTESTING.",
  "AN EXTRAAA A AT THE ENDD.",
  "WORDSWITH—UNUSUAL—DASHES—INSIDE.",
  "ODD’S USE OF APOSTROPHE’S WRONGLY.",
  "END WITH A QUESTION MARKK??",
  "COLONS: ARE: USED: INCORRECTLYY:",
  "QUOTE WITHOUT ENDING MARK “EXAMPLE.",
  "SENTENCE HAS NO ENDING PERIOD",
  "RANDOM GIBBER: ASDLFKJ QWEORUI MNZX.",
  "COFFEEE TASTES BETTR IN THE MORNING.",
  "DEFINATELY IS A COMMON MISSPELLING.",
  "SHE BELEIVES IN HER ABILITIESS.",
  "OCCURED TWICE IN THISS DOCCUMNT.",
  "FREINDSHIP IS SPELT INCORECTLY.",
  "FINALLY, THE LASST LINE IS DONE.",
  "Thiss line has a speling error. ###",
  "The quick brown fox jumps over the lazy dog. ###",
  "I liek to write cod everyday. ###",
  "Spellchecker should detect mispelled wrds. ###",
  "This sentence is perfectly fine. ###",
  "Teh rain in spain falls mainly on the plain. ###",
  "Correct spelling is important in proffesional writing. ###",
  "The computar is running very smoothly. ###",
  "Some words arre repeated repeated incorrectly. ###",
  "English has many weird spellings. ###",
  "Datta integrity is crucial in databases. ###",
  "Som people forget double letters like accomodate. ###",
  "Beutiful day outside with sunshine. ###",
  "The sun set slowly behind the mountan. ###",
  "This is a CORRECTLY capitalized sentence. ###",
  "Check for RANDOM capitalization Errors here. ###",
  "Typing fast can cause speeling mistakes. ###",
  "I have recieve the package today. ###",
  "Simple sentnce with missng vowels. ###",
  "12345 testnumbers insideaword987. ###",
  "Punctuation,test,case,without,spaces. ###",
  "Omg!!!! Too many exclamationsssss. ###",
  "Thisss worrrd shouldd be flaged. ###",
  "CamelCaseWordShouldBeTested. ###",
  "testCASEwithMixedUPletters. ###",
  "LOWERCASE all correct words here. ###",
  "UPPERCASE ALLCORRECTWORDS TOO. ###",
  "MixEd CaSe WIT out Sense. ###",
  "Numberslike2fastshouldbeseparated. ###",
  "The differnce between there and their. ###",
  "Weather or wether the words matter. ###",
  "Thay went to the store yesterday. ###",
  "She doesnt know how to spel \"necessary\". ###",
  "Some ppl use txt spk 4 chatting. ###",
  "CreativeInventedWoordForTesting. ###",
  "An extraaa a at the endd. ###",
  "Wordswith—unusual—dashes—inside. ###",
  "Odd’s use of apostrophe’s wrongly. ###",
  "End with a question markk?? ###",
  "Colons: are: used: incorrectlyy: ###",
  "Quote without ending mark “Example. ###",
  "Sentence has no ending period ###",
  "Random gibber: asdlfkj qweorui mnzx. ###",
  "Coffeee tastes bettr in the morning. ###",
  "Definately is a common misspelling. ###",
  "She beleives in her abilitiess. ###",
  "Occured twice in thiss doccumnt. ###",
  "Freindship is spelt incorectly. ###",
  "Finally, the lasst line is done. ###"
];
